### ISSUE TITLE
doesnt open in Netbeans

### ISSUE THREAD

**Issue by PieGuy7896** [FreedomOp-Development/FreedomOpMod#1]
this doesnt open in netbeans help

**Comment by ImJustLazyGH** [comment]
It's not a netbeans project, sorry.

@PieGuy7896

**Comment by PieGuy7896** [comment]
eclipse?

**Comment by tylerhyperHD** [comment]
It is a netbeans project, it's just that you are probably loading it incorrectly.

**Comment by buildcarter8** [comment]
It can be used in both but preferred use is in eclipse due to the fact that it makes the development quicker

**Comment by tylerhyperHD** [comment]
I'll have to convert it to eclipse maven due to some issues with the build properties files and other stuff. That way we can all get the same thing and we can compile using both eclipse or netbeans.
