### ISSUE TITLE
Using this as a fork on my server

### ISSUE THREAD

**Issue by ghost** [FreedomOp-Development/FreedomOpMod#16]
Hello FreedomOp developers! I was wondering if I could use this mod on my server. I was trying to get TFM-2.14 but i couldn't be arsed. So I remembered carter said this was TFM 2.14 so obviously I was change everything but I want to ask the devs if they want to join the git org for the server.

If so reply say you want to and you will be invited and have owner access.

Goodbye 😄

**Comment by ghost** [comment]
Also, help!!

http://imgur.com/a/0tgX7

**Comment by buildcarter8** [comment]
Yes you have permission i cant help you with that issue tho
