### ISSUE TITLE
Project error: Does not open in netbeans

### ISSUE THREAD

**Issue by DUFCLiam** [FreedomOp-Development/FreedomOpMod#5]
May someone help? It says "No project added"

**Comment by PieGuy7896** [comment]
I had same issue, works in eclipse. I'll assign Tylerhyper, as he made it work for me.

**Comment by tylerhyperHD** [comment]
This project doesn't open in netbeans, it opens in eclipse. For further assistance for this matter, contact @buildcarter8.
