### ISSUE TITLE
What are all the files I need to code in this?

### ISSUE THREAD

**Issue by DUFCLiam** [FreedomOp-Development/FreedomOpMod#7]
Description	Resource	Path	Location	Type
FOPM_PlayerListener cannot be resolved to a type	TotalFreedomMod.java	/FreedomOpMod-master/src/me/StevenLawson/TotalFreedomMod	line 135	Java Problem
The import me.PieGuy7896 cannot be resolved	Command_devtest.java	/FreedomOpMod-master/src/me/StevenLawson/TotalFreedomMod/Commands	line 3	Java Problem
The import me.PieGuy7896 cannot be resolved	Command_fom.java	/FreedomOpMod-master/src/me/StevenLawson/TotalFreedomMod/Commands	line 3	Java Problem
The import me.PieGuy7896 cannot be resolved	TotalFreedomMod.java	/FreedomOpMod-master/src/me/StevenLawson/TotalFreedomMod	line 11	Java Problem

**Comment by PieGuy7896** [comment]
i'm guessing thats something I broke uhh fuck

**Comment by PieGuy7896** [comment]
my fault - fixed
